### ISSUE TITLE
Running  teamcity-messages with node and coverage breaks coverage reporting

### ISSUE THREAD

**Issue by hurrycane** [JetBrains/teamcity-messages#17] opened 2014-03-09 14:44 UTC
Hey guys,

I'm running my python tests under TeamCity with the teamcity-messages plugin. It all works great but it overrides the coverage reports.

If I unset the TEAMCITY_PROJECT_NAME variable it generates the coverage reports if I have it enabled it fails to do so.

My command is:

```
nosetests . --nocapture --with-coverage --cover-package=resources --cover-erase --cover-html-dir=coverage --cover-html
```

My guess is that you don't let any other plugin run after teamcity-messages.

Thanks in advance,
Bogdan

**Comment by malcm** [comment] 2015-01-08 11:54
Just saw the update to 1.9
Poorly there is no change with the coverage. Is it planed that the coverage is also visible in the teamcity coverage page?
Or is there some workaround to visualize the coverage in teamcity?

**Comment by shalupov** [comment] 2015-01-08 11:57
Sorry, it's not yet in 1.9. I plan to fix this issue and also look at #35

**Comment by shalupov** [comment] 2015-01-08 14:24
Actually I can't reproduce it (see test). Do you see broken coverage on 1.9 as well?

**Comment by malcm** [comment] 2015-01-08 16:08
I talk about the direct integration like in the teamcity doc ... https://confluence.jetbrains.com/download/attachments/48105798/CodeCoverage.png
Right now I'm doing it with html export of the coverage and then using it with artifacts. The right integration would be nicer but maybe it's not possible. I'm not completly sure. Becuase on the commandline is normaly a coverage output but not with teamcity-messages enabled.

**Comment by shalupov** [comment] 2015-01-08 16:25
Ok, understood. Could you enable teamcity-messages there (version 1.9)? Will it work after that?

**Comment by shalupov** [comment] 2015-01-30 11:46
@malcm Only by publishing it as a separate tab: https://confluence.jetbrains.com/display/TCD9/Including+Third-Party+Reports+in+the+Build+Results

I plan to publish coverage statistical variables automatically, but not the reports. Maybe I'll write a blog post about HTML reports...

**Comment by jmmills** [comment] 2015-09-09 02:10
Is there a fix for this?

**Comment by shalupov** [comment] 2015-09-09 09:47
A fix for what exactly?

**Comment by shalupov** [comment] 2016-05-21 13:29
Closed this issue. Please open a new one if you have a specific problem or feature request.

**Closed by shalupov** 2016-05-21 13:29 UTC
