### ISSUE TITLE
Teamcity counting pytest setup and teardown methods as tests when using xdist

### ISSUE THREAD

**Issue by joshrlesch** [JetBrains/teamcity-messages#74] opened 2015-09-15 21:51 UTC
I have appium/selenium pytests running on a teamcity build agent. When ran with pytest-xdist with the `-n2` argument. It will triple the test count. I can see in teamcity the test names collected and the setup/teardown for each test is being counted as a test. 

Without the `-n2` is counts correctly. 

So my pytest command looks like `py.test -n2 -v -s` and I have tried without the `-v -s`

and a sample of my build log in teamcity looks like
```
[13:00:33][Step 3/4] [gw0] darwin Python 3.4.3 cwd: /Applications/buildAgent/work/afcaa9d3bd472074/skywalker/SeleniumTests
[13:00:33][Step 3/4] [gw1] darwin Python 3.4.3 cwd: /Applications/buildAgent/work/afcaa9d3bd472074/skywalker/SeleniumTests
[13:00:34][Step 3/4] [gw1] Python 3.4.3 (default, Apr 27 2015, 19:08:17)  -- [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)]
[13:00:34][Step 3/4] [gw0] Python 3.4.3 (default, Apr 27 2015, 19:08:17)  -- [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)]
[13:00:35][Step 3/4] gw0 [49] / gw1 [49]
[13:00:35][Step 3/4] 
[13:00:35][Step 3/4] scheduling tests via LoadScheduling
[13:00:35][Step 3/4] 
[13:00:35][Step 3/4] mobile_apps/modi/test_ipad_modi.py::TestIpad2::test_admin_login <- mobile_apps/modi/tests_common_modi.py 
[13:00:35][Step 3/4] mobile_apps.modi.test_ipad_modi.TestIpad2.test_admin_login (50s)
[13:00:35][Step 3/4] 
[13:00:35][Step 3/4] mobile_apps/modi/test_ipad_modi.py::TestIpad2::test_football_athlete_menu <- mobile_apps/modi/tests_common_modi.py 
[13:00:35][Step 3/4] mobile_apps.modi.test_ipad_modi.TestIpad2.test_football_athlete_menu (52s)
[13:01:19][Step 3/4] 
[13:01:19][Step 3/4] mobile_apps.modi.test_ipad_modi.TestIpad2.test_football_athlete_menu_setup
[13:01:19][Step 3/4] 
[13:01:19]
[mobile_apps.modi.test_ipad_modi.TestIpad2.test_football_athlete_menu_setup] [Test Output]


[13:01:19][Step 3/4] 
[13:01:19]
[mobile_apps.modi.test_ipad_modi.TestIpad2.test_football_athlete_menu_setup] [Test Error Output]
[13:01:19][Step 3/4] 
[13:01:20][Step 3/4] 
[13:01:20][Step 3/4] mobile_apps.modi.test_ipad_modi.TestIpad2.test_admin_login_setup
[13:01:20][Step 3/4] 
[13:01:20]
[mobile_apps.modi.test_ipad_modi.TestIpad2.test_admin_login_setup] [Test Output]


[13:01:20][Step 3/4] 
[13:01:20]
[mobile_apps.modi.test_ipad_modi.TestIpad2.test_admin_login_setup] [Test Error Output]
[13:01:20][Step 3/4] 
[13:01:25][Step 3/4] 
[13:01:25][Step 3/4] [gw1] PASSED mobile_apps/modi/test_ipad_modi.py::TestIpad2::test_admin_login <- mobile_apps/modi/tests_common_modi.py 
[13:01:25]
[mobile_apps.modi.test_ipad_modi.TestIpad2.test_admin_login] [Test Error Output]
INFO 2015-09-14 13:01:04,999 base:803:log_page_load: Page Loaded: LoginScreenView
INFO 2015-09-14 13:01:07,721 base:803:log_page_load: Page Loaded: HomePageView
INFO 2015-09-14 13:01:09,720 base_modi:66:open_menu: Menu already open, skipping...
INFO 2015-09-14 13:01:09,722 base:803:log_page_load: Page Loaded: MainMenuView
[13:01:25][Step 3/4] 
[13:01:26][Step 3/4] 
[13:01:26][Step 3/4] mobile_apps.modi.test_ipad_modi.TestIpad2.test_admin_login_teardown
[13:01:26][Step 3/4] 
[13:01:26]
[mobile_apps.modi.test_ipad_modi.TestIpad2.test_admin_login_teardown] [Test Output]


[13:01:26][Step 3/4] 
[13:01:26]
[mobile_apps.modi.test_ipad_modi.TestIpad2.test_admin_login_teardown] [Test Error Output]
INFO 2015-09-14 13:01:10,703 base_modi:66:open_menu: Menu already open, skipping...
INFO 2015-09-14 13:01:10,703 base:803:log_page_load: Page Loaded: MainMenuView
[13:01:26][Step 3/4] 
[13:01:26][Step 3/4] 
```

Has anybody seen a situation like this?

Python3.4
pytest = 2.7.2
teamcity-messages = 1.16
TeamCity = 8.1.4

**Comment by frishberg** [comment] 2015-09-17 14:33
Yes, I am seeing this too. Similar output to yours. It only happens when xdist is enabled.

**Comment by frishberg** [comment] 2015-09-17 14:35
teamcity-messages version 1.16, pytest 2.7.3, Python 3.4.3, TeamCity 9.1.1

**Comment by joshrlesch** [comment] 2015-09-17 18:38
Is this a bug within teamcity buildlog or the teamcity-messages plugin?

**Comment by shalupov** [comment] 2015-09-17 21:00
I'll try to investigate it this weekend

**Comment by shalupov** [comment] 2015-09-20 11:40
Looks like xdist forces py.test to capture setup and teardown output, which converts to setup/teardown tests with output.

You may reproduce it without xdist with "--capture=fd" option instead of "-s".

I still need a place to show output from setup/teardown, so suggestions are welcome.

**Comment by shalupov** [comment] 2015-10-17 17:52
Closing the issue since no feedback for 27 days

**Closed by shalupov** 2015-10-17 17:52 UTC

**Comment by ashahba** [comment] 2016-01-20 03:58
I'm seeing this error with "TeamCity Enterprise 9.1.3 (build 37176)", "pytest (2.8.5)", "pytest-xdist (1.13.1) " and "teamcity-messages (1.17)". 

Any plans to fix this in the future?

**Comment by shalupov** [comment] 2016-01-23 21:28
Yes, as a part of #91
